/**
 * Tiered content bank for programmatic puppy description assembly.
 * Tokens: [Name], [Age], [Breed], [Color], [Subject], [Object], [Possessive]
 * Structured for code-first use; interfaces are DB-migration ready.
 */

export type ContentLine = {
  id: string;
  text: string;
  idea?: string;
  tone?: string;
};

export type Tier1Content = ContentLine[];
export type Tier2Content = Record<'8-10' | '10-15', ContentLine[]>;
export type Tier3Content = Record<string, ContentLine[]>;
export type Tier4Content = ContentLine[];
export type Tier5Content = ContentLine[];

/** Tier 1: Introductions (30 variations) */
export const TIER1_INTRODUCTIONS: Tier1Content = [
  { id: 't1-01', text: 'Meet [Name], a beautiful [Age]-old [Color] [Breed] who is ready to bring warmth and joy to your home.' },
  { id: 't1-02', text: 'Say hello to [Name], a stunning [Color] [Breed] who is [Age] old and full of happy puppy energy.' },
  { id: 't1-03', text: 'Introducing [Name], an affectionate [Age]-old [Color] [Breed] with a heart full of love to share.', idea: 'affection' },
  { id: 't1-04', text: 'If you are searching for a new best friend, [Name] is a gorgeous [Age]-old [Color] [Breed] waiting to meet you.' },
  { id: 't1-05', text: 'Get ready to welcome [Name], a playful and sweet [Age]-old [Color] [Breed], into your daily routine.', tone: 'playful' },
  { id: 't1-06', text: '[Name] is a precious [Color] [Breed] at [Age] of age, already showing a friendly and lovable personality.', idea: 'social' },
  { id: 't1-07', text: 'This [Age]-old [Color] [Breed] named [Name] is a total sweetheart looking for a loving home to call [Possessive] own.' },
  { id: 't1-08', text: '[Name] is a striking [Color] [Breed], currently [Age] old, and always seems to brighten the room.' },
  { id: 't1-09', text: 'Please welcome [Name], a charming [Age]-old [Color] [Breed] who is just as smart as [Subject] is cute.' },
  { id: 't1-10', text: '[Name] is an elegant [Color] [Breed] of [Age], ready to begin life with a caring family.' },
  { id: 't1-11', text: 'Looking for a [Color] companion? [Name] is a [Age]-old [Breed] with a truly gentle and kind nature.', tone: 'calm' },
  { id: 't1-12', text: '[Name] is a vibrant [Age]-old [Breed] in a lovely [Color] coat, eager to make new memories with you.', tone: 'active' },
  { id: 't1-13', text: 'Meet our [Color] [Breed] puppy, [Name], who is [Age] old and loves being around people.', idea: 'social' },
  { id: 't1-14', text: '[Name] is a [Age]-old [Color] [Breed] who is just beginning to explore the world with curiosity.' },
  { id: 't1-15', text: 'This [Color] [Breed] named [Name] is [Age] old and has the softest, most loving heart.', idea: 'bonding' },
  { id: 't1-16', text: '[Name] is a [Age]-old [Color] [Breed] who captures attention with [Possessive] bright and happy spirit.' },
  { id: 't1-17', text: 'Say hi to [Name], a [Age]-old [Color] [Breed] who is well-socialized and ready to settle into a new home.', idea: 'social' },
  { id: 't1-18', text: '[Name] is a [Color] [Breed] at [Age] old, showing many of the qualities families love about this breed.' },
  { id: 't1-19', text: 'We are excited to introduce [Name], a [Age]-old [Color] [Breed] with a sweet personality and a bright future.' },
  { id: 't1-20', text: '[Name] is a [Color] [Breed] puppy of [Age], already showing the loving nature this breed is often known for.', idea: 'bonding' },
  { id: 't1-21', text: 'Take a look at [Name], our newest [Color] [Breed] arrival who is [Age] old and always ready to play.', tone: 'playful' },
  { id: 't1-22', text: '[Name] is a delightful [Age]-old [Color] [Breed] with a temperament that is as bright as [Possessive] beautiful coat.' },
  { id: 't1-23', text: 'We are proud to present [Name], a lovely [Color] [Breed] who is [Age] and full of puppy charm.' },
  { id: 't1-24', text: '[Name] is a [Age]-old [Color] [Breed] who has been surrounded by attention and affection since the day [Subject] arrived.', idea: 'bonding' },
  { id: 't1-25', text: 'Meet the lovable [Name], a [Color] [Breed] of [Age] who is searching for a lifetime of snuggles and affection.', tone: 'cuddly' },
  { id: 't1-26', text: '[Name] is a standout [Color] [Breed] puppy at [Age] old, with a sweet and easygoing personality.', tone: 'calm' },
  { id: 't1-27', text: 'Here is [Name], an adventurous [Age]-old [Color] [Breed] who is looking for a family to share life with.', tone: 'active' },
  { id: 't1-28', text: '[Name] is a gorgeous [Color] [Breed] who is [Age] old and appears happy, well cared for, and full of puppy charm.' },
  { id: 't1-29', text: 'Introducing the one-of-a-kind [Name], a [Age]-old [Color] [Breed] with a heart full of love and a wagging tail.' },
  { id: 't1-30', text: '[Name] is a friendly [Color] [Breed] of [Age], eager to join a family that values companionship.', idea: 'social' },
];

/** Tier 2: Age-specific (8–10 weeks) */
export const TIER2_AGE_8_10: ContentLine[] = [
  { id: 't2-8-01', text: 'At this stage, [Name] is focused on building confidence and discovering the world around [Object].' },
  { id: 't2-8-02', text: 'Being [Age] old, [Subject] is at a wonderful age for learning and taking in new experiences.' },
  { id: 't2-8-03', text: '[Name] relies on plenty of nap time to support all the growing [Subject] is doing at [Age].' },
  { id: 't2-8-04', text: '[Subject] is getting steadier on [Possessive] feet and finding [Possessive] balance during daily play sessions.' },
  { id: 't2-8-05', text: 'At this young age, [Name] naturally loves to stay close to people and looks for reassurance now and then.', idea: 'bonding' },
  { id: 't2-8-06', text: '[Subject] is very open to learning new things and building trust through gentle handling right now.' },
  { id: 't2-8-07', text: 'With a typical puppy attention span, [Name] does best with short and happy interactions at [Age] old.' },
  { id: 't2-8-08', text: '[Subject] is starting to understand the household routine and responds well to kind guidance.' },
  { id: 't2-8-09', text: 'During this phase, [Name] tends to follow [Possessive] people everywhere, which makes early bonding especially easy.', idea: 'bonding' },
  { id: 't2-8-10', text: '[Subject] is currently at the age where everything goes in [Possessive] mouth, so soft chew toys are a big hit.' },
  { id: 't2-8-11', text: 'As a young puppy, [Name] is busy learning how to communicate and bond with [Possessive] new family.', idea: 'bonding' },
  { id: 't2-8-12', text: '[Subject] is building a foundation of trust and being introduced to new sights and sounds.' },
  { id: 't2-8-13', text: 'At [Age], [Name] is at a great age to form a deep and lasting bond with a new family.', idea: 'bonding' },
  { id: 't2-8-14', text: '[Subject] is learning how to be a little more independent while still staying very curious.' },
  { id: 't2-8-15', text: '[Name] is at a great age to start learning house rules through praise, routine, and patience.' },
  { id: 't2-8-16', text: '[Subject] is just beginning to recognize [Possessive] name and may tilt [Possessive] head when called.' },
  { id: 't2-8-17', text: 'At [Age], [Name] is finding [Possessive] voice and may let out a tiny bark when [Subject] gets excited.' },
  { id: 't2-8-18', text: '[Subject] is quickly learning which toys are [Possessive] own and enjoys finding new favorites.' },
  { id: 't2-8-19', text: '[Name] spends [Possessive] awake time at [Age] exploring different textures and spaces around the house.' },
  { id: 't2-8-20', text: '[Subject] is very nose-oriented right now and loves to sniff and greet everyone who comes by.', idea: 'social' },
  { id: 't2-8-21', text: 'At this young age, [Name] finds a lot of comfort in being held and feeling close to [Possessive] people.', tone: 'cuddly' },
  { id: 't2-8-22', text: '[Subject] is being introduced to a regular potty routine and is showing nice early progress.' },
  { id: 't2-8-23', text: '[Name] is at a stage where every little sound feels new and interesting.' },
  { id: 't2-8-24', text: '[Subject] is sensitive to touch at [Age] and often enjoys a soft brushing during grooming time.' },
  { id: 't2-8-25', text: 'At this point in life, [Name] is like a little sponge, ready for love, routine, and gentle training.' },
];

/** Tier 2: Age-specific (10–15 weeks) */
export const TIER2_AGE_10_15: ContentLine[] = [
  { id: 't2-10-01', text: 'Having grown a bit more coordinated, [Name] is now ready for more structured and fun playtime.', tone: 'playful' },
  { id: 't2-10-02', text: '[Subject] is starting to focus for longer periods, which is great for learning basic manners.' },
  { id: 't2-10-03', text: 'At this stage, [Name] is often very motivated by treats and eager to learn.' },
  { id: 't2-10-04', text: '[Subject] is exploring [Possessive] world with more confidence and a healthy sense of adventure.', tone: 'active' },
  { id: 't2-10-05', text: 'With a steady routine in place, [Name] is ready to begin meeting new people and seeing new places.', idea: 'social' },
  { id: 't2-10-06', text: '[Subject] may be doing some teething right now and benefits from having good chew toys nearby.' },
  { id: 't2-10-07', text: 'During this phase, [Name] is often settling into a regular sleep schedule that fits the home well.' },
  { id: 't2-10-08', text: '[Subject] is often showing better control, which can make potty training go more smoothly at this age.' },
  { id: 't2-10-09', text: 'At [Age], [Name] is ready for slightly longer walks to help use up some of that puppy energy.', tone: 'active' },
  { id: 't2-10-10', text: '[Subject] is learning the rhythm of the household and usually adapts well to daily routines.' },
  { id: 't2-10-11', text: 'Showing more stamina, [Name] now enjoys a good game of fetch or a little outdoor exploration.', tone: 'active' },
  { id: 't2-10-12', text: '[Subject] is at a great age for learning where [Subject] is allowed to go in the home.' },
  { id: 't2-10-13', text: 'At this point, [Name] often shows a clever side when given a puzzle toy or hidden treat.' },
  { id: 't2-10-14', text: '[Subject] is refining how [Subject] plays and learning how to be gentle and polite with people.' },
  { id: 't2-10-15', text: 'With [Possessive] mind growing so fast, [Name] loves having things to do to stay happy and occupied.' },
  { id: 't2-10-16', text: '[Subject] is now often able to focus on simple commands like "sit" for a few moments at a time.' },
  { id: 't2-10-17', text: 'At [Age], [Name] is usually becoming more confident when meeting other friendly dogs.', idea: 'social' },
  { id: 't2-10-18', text: '[Subject] is beginning to show [Possessive] own personality and clear preferences for certain games.' },
  { id: 't2-10-19', text: '[Name] is at the age where [Subject] can start practicing how to walk nicely on a leash.' },
  { id: 't2-10-20', text: '[Subject] is increasingly curious about the outdoors and often enjoys short car rides.' },
  { id: 't2-10-21', text: 'At this age, [Name] is often a fast learner who enjoys having a little task to do.' },
  { id: 't2-10-22', text: '[Subject] is showing more independence and is often happy to play with a toy alone for a bit.' },
  { id: 't2-10-23', text: '[Name] is now old enough to start practicing a little patience before mealtime.' },
  { id: 't2-10-24', text: '[Subject] is usually very social at [Age] and loves being right in the middle of family activity.', idea: 'social' },
  { id: 't2-10-25', text: 'At this stage, [Name] is often the perfect mix of playful energy and growing maturity.', tone: 'playful' },
];

export const TIER2_BY_AGE: Tier2Content = {
  '8-10': TIER2_AGE_8_10,
  '10-15': TIER2_AGE_10_15,
};

/** Tier 3: Breed-specific. Keys match normalized breed names; "Poodle" covers Poodle, Mini Poodle, Mini Doodle. */
const TIER3_GOLDEN_DOODLES: ContentLine[] = [
  { id: 't3-gd-01', text: 'Commonly loved for their smarts, [Name] tends to be easy to teach and quick to learn.' },
  { id: 't3-gd-02', text: '[Subject] often has the kind of coat many families appreciate for its lower-shedding qualities.' },
  { id: 't3-gd-03', text: 'This breed is often loved for its affectionate nature and lively spirit.', idea: 'affection' },
  { id: 't3-gd-04', text: '[Name] usually enjoys games that keep [Possessive] mind busy and engaged.' },
  { id: 't3-gd-05', text: '[Subject] tends to be very social and often greets people with a friendly wag.', idea: 'social' },
  { id: 't3-gd-06', text: '[Name] often has a natural love for retrieving, which makes backyard play especially fun.', tone: 'active' },
  { id: 't3-gd-07', text: 'This breed usually does best when given both physical activity and things to think about.' },
  { id: 't3-gd-08', text: '[Subject] often has an active side that fits well with families who enjoy walks and outings.', tone: 'active' },
  { id: 't3-gd-09', text: 'Known for being intuitive, [Name] often seems very tuned in to the people around [Object].' },
  { id: 't3-gd-10', text: '[Subject] tends to have a gentle way of playing with toys and people alike.' },
  { id: 't3-gd-11', text: '[Name] usually adapts well to different home routines and family lifestyles.' },
  { id: 't3-gd-12', text: 'This breed can do well with other pets when introduced thoughtfully and given guidance.' },
  { id: 't3-gd-13', text: '[Subject] is often motivated by snacks, which can make teaching manners a lot of fun.' },
  { id: 't3-gd-14', text: '[Name] may have an interest in water and might enjoy splashing around on warm days.' },
  { id: 't3-gd-15', text: 'This breed usually benefits from regular brushing to keep that beautiful [Color] coat looking its best.' },
  { id: 't3-gd-16', text: '[Name] often brings together a loving heart and a bright, curious mind.', idea: 'bonding' },
  { id: 't3-gd-17', text: '[Subject] tends to be agile and often enjoys active play in the yard.', tone: 'active' },
  { id: 't3-gd-18', text: 'As a [Breed], [Name] is often loved for a patient and affectionate nature that many families appreciate.', idea: 'affection' },
  { id: 't3-gd-19', text: '[Subject] typically has a sturdy frame that is made for both play and snuggles.', tone: 'cuddly' },
  { id: 't3-gd-20', text: '[Name] is often very observant and may quickly learn the rhythm of your home.' },
  { id: 't3-gd-21', text: 'This breed is often called a "people dog" because they love being close to their family.', idea: 'bonding' },
  { id: 't3-gd-22', text: '[Subject] often shows a comforting side and may rest [Possessive] chin in your lap when [Subject] wants to be near you.', tone: 'cuddly' },
  { id: 't3-gd-23', text: '[Name] usually moves with a happy, confident energy that is fun to watch.' },
  { id: 't3-gd-24', text: 'As a [Color] [Breed], [Subject] is often just as lovely to look at as [Subject] is sweet to be around.' },
  { id: 't3-gd-25', text: '[Subject] often shows the mix of smarts, affection, and playfulness that makes this breed so popular.', idea: 'affection' },
];

const TIER3_SHIH_TZU: ContentLine[] = [
  { id: 't3-st-01', text: 'Bred mainly for companionship, [Name] is known for being a loving and devoted little friend.', idea: 'bonding' },
  { id: 't3-st-02', text: '[Subject] has that classic sturdy little build that can make a Shih Tzu a nice fit for smaller homes.' },
  { id: 't3-st-03', text: 'This breed is loved for a soft coat that stays beautiful with regular brushing and care.' },
  { id: 't3-st-04', text: '[Name] usually does not need huge amounts of exercise and is often happy with a few short walks.', tone: 'calm' },
  { id: 't3-st-05', text: '[Subject] often has a confident and watchful way about [Object].' },
  { id: 't3-st-06', text: 'This breed is known for being very affectionate and often prefers to spend time close to family.', idea: 'affection' },
  { id: 't3-st-07', text: '[Name] usually has a peaceful nature and can do well in a calm home environment.', tone: 'calm' },
  { id: 't3-st-08', text: '[Subject] often uses cute little sounds to let you know when [Subject] is happy or wants attention.' },
  { id: 't3-st-09', text: 'This breed is famously loyal and may follow you from room to room just to stay close.', idea: 'bonding' },
  { id: 't3-st-10', text: '[Name] often settles in well to a quieter routine and enjoys a relaxed lifestyle.', tone: 'calm' },
  { id: 't3-st-11', text: '[Subject] may need a little extra grooming to keep that [Color] hair neat around [Possessive] face.' },
  { id: 't3-st-12', text: 'Underneath that pretty [Color] coat, [Name] usually has a strong and sturdy little body.' },
  { id: 't3-st-13', text: '[Subject] is often polite with new people but usually saves [Possessive] biggest excitement for family.', idea: 'social' },
  { id: 't3-st-14', text: 'This breed often responds well to short and positive training sessions.' },
  { id: 't3-st-15', text: '[Name] naturally loves a soft place to rest and usually finds the coziest spot in the room.', tone: 'cuddly' },
  { id: 't3-st-16', text: '[Subject] often carries [Object]self with a little pride, almost like a tiny royal companion.' },
  { id: 't3-st-17', text: 'As a [Breed], [Name] can be quite brave for [Possessive] size.' },
  { id: 't3-st-18', text: '[Subject] is often a more easygoing puppy who is happy with a stroll and a nap.', tone: 'calm' },
  { id: 't3-st-19', text: '[Name] is known for those big, dark eyes that often seem full of sweetness.' },
  { id: 't3-st-20', text: '[Subject] is often perfectly happy to spend a rainy afternoon snuggling on the couch.', tone: 'cuddly' },
  { id: 't3-st-21', text: 'This breed is naturally neat and often seems to like staying clean.' },
  { id: 't3-st-22', text: '[Name] often masters the classic head tilt that wins everybody over.' },
  { id: 't3-st-23', text: '[Subject] can have an independent side but usually comes right back for affection.' },
  { id: 't3-st-24', text: 'As a [Color] [Breed], [Name] often turns heads wherever [Subject] goes.' },
  { id: 't3-st-25', text: '[Subject] is often described as the kind of dog that forms a very deep bond with [Possessive] people.', idea: 'bonding' },
];

const TIER3_LABRADOODLES: ContentLine[] = [
  { id: 't3-lab-01', text: '[Name] often shows a great mix of playfulness, intelligence, and eagerness to connect with people.', idea: 'social' },
  { id: 't3-lab-02', text: '[Subject] usually has an active and athletic build that suits a fun and busy lifestyle.', tone: 'active' },
  { id: 't3-lab-03', text: 'This breed often has a coat many families appreciate for its lower-shedding qualities.' },
  { id: 't3-lab-04', text: '[Name] may have a natural love for water and could enjoy splashing and swimming as [Subject] grows.' },
  { id: 't3-lab-05', text: '[Subject] is often quick to learn, which can make puppy training especially rewarding.' },
  { id: 't3-lab-06', text: 'This breed is loved for a cheerful personality that can brighten up the whole home.' },
  { id: 't3-lab-07', text: '[Name] usually needs some daily activity to help use up [Possessive] natural puppy energy.', tone: 'active' },
  { id: 't3-lab-08', text: '[Subject] often does well in active environments and tends to be friendly with new people.', idea: 'social' },
  { id: 't3-lab-09', text: 'This breed often enjoys scent games and activities that make use of [Possessive] nose.' },
  { id: 't3-lab-10', text: '[Name] usually builds a close bond with people through play, training, and shared routines.', idea: 'bonding' },
  { id: 't3-lab-11', text: '[Subject] often handles new experiences with curiosity and a resilient attitude.' },
  { id: 't3-lab-12', text: 'This breed usually thrives when given both movement and mental stimulation.' },
  { id: 't3-lab-13', text: '[Name] is often very tuned in to what the people around [Object] are doing.' },
  { id: 't3-lab-14', text: '[Subject] typically has a solid and sturdy build that makes [Object] a fun play partner.' },
  { id: 't3-lab-15', text: 'This breed often shows affection by leaning into you when [Subject] wants to feel close.', idea: 'affection' },
  { id: 't3-lab-16', text: '[Name] is often an all-around companion, ready for activity or quiet time at home.' },
  { id: 't3-lab-17', text: '[Subject] usually has a curious mind and likes investigating new things around the house.' },
  { id: 't3-lab-18', text: 'As a [Breed], [Name] is often very social and enjoys meeting both people and other dogs.', idea: 'social' },
  { id: 't3-lab-19', text: '[Subject] is often quite athletic and enjoys room to run and play.', tone: 'active' },
  { id: 't3-lab-20', text: '[Name] is often a quick thinker who enjoys puzzles and little tasks.' },
  { id: 't3-lab-21', text: 'This breed is known for a tail that can wag with [Possessive] whole body.' },
  { id: 't3-lab-22', text: '[Subject] is often a loyal companion who enjoys being part of family routines and outings.' },
  { id: 't3-lab-23', text: '[Name] often seems to sense when someone needs extra attention or affection.', idea: 'affection' },
  { id: 't3-lab-24', text: 'As a [Color] [Breed], [Subject] often has a rich coat that is both soft and eye-catching.' },
  { id: 't3-lab-25', text: '[Subject] is often a great match for active families looking for a lively and loving companion.', tone: 'active' },
];

const TIER3_MALTESE: ContentLine[] = [
  { id: 't3-mal-01', text: '[Name] is a classic Maltese, known for that beautiful and elegant coat many families love.' },
  { id: 't3-mal-02', text: '[Subject] may be small, but [Subject] often has a brave and confident personality.' },
  { id: 't3-mal-03', text: 'This breed usually does very well as an indoor companion and can be a nice fit for smaller homes.' },
  { id: 't3-mal-04', text: '[Name] is often very devoted to [Possessive] family and likes being part of daily life.', idea: 'bonding' },
  { id: 't3-mal-05', text: '[Subject] often has a gentle and polite way about [Object] that makes [Object] a joy to have around.' },
  { id: 't3-mal-06', text: 'This breed is often alert and may let you know when someone is at the door.' },
  { id: 't3-mal-07', text: '[Name] typically benefits from daily brushing to keep that [Color] coat soft and neat.' },
  { id: 't3-mal-08', text: '[Subject] is often nimble and may enjoy playful games around the living room.', tone: 'playful' },
  { id: 't3-mal-09', text: 'As a [Breed], [Name] is known for staying playful and affectionate for many years.', idea: 'affection' },
  { id: 't3-mal-10', text: '[Subject] is often a velcro-style companion who feels happiest when close to you.', idea: 'bonding' },
  { id: 't3-mal-11', text: '[Name] often has a very sweet and expressive face that is hard to resist.' },
  { id: 't3-mal-12', text: '[Subject] can be sensitive and usually responds best to kind and encouraging words.' },
  { id: 't3-mal-13', text: 'This breed has a long history as a lap dog and often takes snuggle time very seriously.', tone: 'cuddly' },
  { id: 't3-mal-14', text: '[Name] is often naturally well-mannered and carries [Object]self with a bit of grace.' },
  { id: 't3-mal-15', text: '[Subject] is often easy to take along on errands or visits.' },
  { id: 't3-mal-16', text: '[Name] is often a fast learner when it comes to fun indoor tricks.' },
  { id: 't3-mal-17', text: '[Subject] often has a playful side and may enjoy games with favorite toys.', tone: 'playful' },
  { id: 't3-mal-18', text: 'This breed is famously loyal and often builds a deep bond with [Possessive] favorite person.', idea: 'bonding' },
  { id: 't3-mal-19', text: '[Name] is a low-shedding companion, which many families appreciate in the home.' },
  { id: 't3-mal-20', text: '[Subject] often has a big heart in a small body and does not let [Possessive] size hold [Object] back.' },
  { id: 't3-mal-21', text: '[Name] is often very touch-oriented and usually loves being pampered and brushed.', tone: 'cuddly' },
  { id: 't3-mal-22', text: '[Subject] often has a peaceful spirit that can bring a calm feeling to the room.', tone: 'calm' },
  { id: 't3-mal-23', text: 'As a [Color] [Breed], [Name] is often a timeless little beauty.' },
  { id: 't3-mal-24', text: '[Subject] is often very bright and may "talk" with expressive little sounds.' },
  { id: 't3-mal-25', text: '[Name] is often the perfect choice for someone looking for a devoted companion.', idea: 'bonding' },
];

const TIER3_POODLE: ContentLine[] = [
  { id: 't3-poo-01', text: '[Name] is often a star when it comes to learning and usually picks up new things with ease.' },
  { id: 't3-poo-02', text: '[Subject] usually has that famous curly coat many families appreciate for its lower-shedding qualities.' },
  { id: 't3-poo-03', text: 'This breed is often active at heart and thrives when given things to do.', tone: 'active' },
  { id: 't3-poo-04', text: '[Name] is often very willing to learn and usually works hard for praise and treats.' },
  { id: 't3-poo-05', text: '[Subject] often moves with a light and graceful step that shows off [Possessive] athletic side.' },
  { id: 't3-poo-06', text: 'This breed is known for being observant and may learn your routine very quickly.' },
  { id: 't3-poo-07', text: '[Name] typically needs regular grooming to keep that [Color] coat healthy and soft.' },
  { id: 't3-poo-08', text: '[Subject] is often a versatile companion who can enjoy both outdoor fun and quiet time at home.' },
  { id: 't3-poo-09', text: 'As a [Breed], [Name] is often very intuitive and may seem tuned in to your mood.' },
  { id: 't3-poo-10', text: '[Subject] is usually social with family but may be a little reserved at first with new people.', idea: 'social' },
  { id: 't3-poo-11', text: '[Name] often has a sturdy and athletic build that gives [Object] plenty of energy for play.', tone: 'active' },
  { id: 't3-poo-12', text: '[Subject] is often a great problem-solver who enjoys treat games and little challenges.' },
  { id: 't3-poo-13', text: 'This breed is naturally neat and often seems to prefer staying clean.' },
  { id: 't3-poo-14', text: '[Name] is often an excellent communicator, using [Possessive] eyes and body language to show what [Subject] wants.' },
  { id: 't3-poo-15', text: '[Subject] is often very loyal to [Possessive] people and stays aware of what is happening at home.' },
  { id: 't3-poo-16', text: '[Name] is often a quick thinker and may learn a new trick in just a few tries.' },
  { id: 't3-poo-17', text: '[Subject] often has a playful and slightly goofy side that keeps the family smiling.', tone: 'playful' },
  { id: 't3-poo-18', text: 'This breed is often loved for being active, bright, and full of personality.' },
  { id: 't3-poo-19', text: '[Name] can be a sensitive soul and usually does best with positive and gentle training.' },
  { id: 't3-poo-20', text: '[Subject] is often very adaptable and can settle into many kinds of home environments.' },
  { id: 't3-poo-21', text: '[Name] is often a real beauty in that [Color] coat, with a look that stands out.' },
  { id: 't3-poo-22', text: '[Subject] is often a people-focused dog who would rather be near family than off alone.', idea: 'bonding' },
  { id: 't3-poo-23', text: '[Name] usually has great focus and often gives you [Possessive] full attention when you speak.' },
  { id: 't3-poo-24', text: 'As a [Breed], [Subject] is a classic favorite for a reason, combining intelligence with charm.' },
  { id: 't3-poo-25', text: '[Name] is usually ready to be your partner in anything, from a walk to a quiet nap nearby.' },
];

const TIER3_CHIHUAHUA: ContentLine[] = [
  { id: 't3-chi-01', text: '[Name] often has a very big personality in a very tiny body.' },
  { id: 't3-chi-02', text: '[Subject] is often fiercely loyal to [Possessive] family and may become your devoted little shadow.', idea: 'bonding' },
  { id: 't3-chi-03', text: 'This breed is known for being smart and quick-witted, often finding a way to charm extra attention.' },
  { id: 't3-chi-04', text: '[Name] is often the perfect travel buddy, fitting easily into a carrier or cozy car seat.' },
  { id: 't3-chi-05', text: '[Subject] usually loves warmth and will often find the sunniest spot in the house.' },
  { id: 't3-chi-06', text: 'This breed is known for living many happy years with the right care and companionship.' },
  { id: 't3-chi-07', text: '[Name] is usually very affectionate with [Possessive] people and loves to snuggle close.', idea: 'affection' },
  { id: 't3-chi-08', text: '[Subject] often has a brave little heart and may let you know if [Subject] hears something new.' },
  { id: 't3-chi-09', text: 'As a [Breed], [Name] is often very expressive and uses those big eyes to say a lot.' },
  { id: 't3-chi-10', text: '[Subject] is often lower-maintenance when it comes to exercise and may be happy with indoor play and short walks.', tone: 'calm' },
  { id: 't3-chi-11', text: '[Name] is often perfectly content spending the day close by your side.', idea: 'bonding' },
  { id: 't3-chi-12', text: '[Subject] is usually very adaptable and can settle well even in a smaller living space.' },
  { id: 't3-chi-13', text: 'This breed is naturally alert and often acts like a tiny watchdog around the home.' },
  { id: 't3-chi-14', text: '[Name] often has a quirky and fun-loving spirit that keeps life interesting.', tone: 'playful' },
  { id: 't3-chi-15', text: '[Subject] can be a little selective with new people but is often deeply devoted once comfortable.', idea: 'social' },
  { id: 't3-chi-16', text: '[Name] is often a master at finding the softest blankets and making a little nest.', tone: 'cuddly' },
  { id: 't3-chi-17', text: '[Subject] often has a light and graceful way of moving that is fun to watch.' },
  { id: 't3-chi-18', text: 'This breed is often very clever and can learn plenty of fun little tricks.' },
  { id: 't3-chi-19', text: '[Name] is often a one-person-style dog at heart and loves being close to [Possessive] favorite human.', idea: 'bonding' },
  { id: 't3-chi-20', text: '[Subject] often stays lively and full of personality for many years.' },
  { id: 't3-chi-21', text: '[Name] is a [Color] beauty who is just as unique as [Subject] is small.' },
  { id: 't3-chi-22', text: '[Subject] is often a very clean little dog and may dislike wet or messy paws.' },
  { id: 't3-chi-23', text: '[Name] is often a spirited little soul who brings a lot of personality into daily life.' },
  { id: 't3-chi-24', text: '[Subject] often acts much bigger than [Subject] really is.' },
  { id: 't3-chi-25', text: '[Name] is often a loyal best friend who loves with everything [Subject] has.', idea: 'bonding' },
];

const TIER3_YORKIES: ContentLine[] = [
  { id: 't3-york-01', text: '[Name] often has the brave and spunky heart of a true terrier in a very small package.' },
  { id: 't3-york-02', text: '[Subject] usually has a silky coat that many people compare more to hair than fur.' },
  { id: 't3-york-03', text: 'This breed is known for being curious and usually loves exploring every corner of the home.' },
  { id: 't3-york-04', text: '[Name] is often a big dog in a small body, with a bold and adventurous personality.', tone: 'active' },
  { id: 't3-york-05', text: '[Subject] is often very affectionate and may even dance on [Possessive] back legs for attention.', idea: 'affection' },
  { id: 't3-york-06', text: 'This breed is low-shedding and is often appreciated by families looking for an easier coat in the home.' },
  { id: 't3-york-07', text: '[Name] is often very smart and usually responds well to fun, game-based training.' },
  { id: 't3-york-08', text: '[Subject] often has a busy little personality and likes having toys to stay occupied.', tone: 'playful' },
  { id: 't3-york-09', text: 'As a [Breed], [Name] is famously loyal and may stick close to you throughout the day.', idea: 'bonding' },
  { id: 't3-york-10', text: '[Subject] is usually a great size for travel and loves being included in family outings.' },
  { id: 't3-york-11', text: '[Name] often has an alert and feisty nature that keeps things interesting.' },
  { id: 't3-york-12', text: '[Subject] is often quite nimble and can be surprisingly fast when chasing a toy.', tone: 'active' },
  { id: 't3-york-13', text: 'This breed is naturally vocal and may happily "talk" when excited.' },
  { id: 't3-york-14', text: '[Name] is a [Color] jewel who benefits from regular grooming to keep that coat looking silky.' },
  { id: 't3-york-15', text: '[Subject] is often very brave and may bark at anything [Subject] thinks needs reporting.' },
  { id: 't3-york-16', text: '[Name] often has a sweet and slightly mischievous side that keeps everybody smiling.', tone: 'playful' },
  { id: 't3-york-17', text: '[Subject] is usually perfectly happy spending the evening curled up nearby.', tone: 'cuddly' },
  { id: 't3-york-18', text: 'This breed is often very observant and may quickly learn household routines.' },
  { id: 't3-york-19', text: '[Name] is often a social little butterfly who enjoys being the center of attention.', idea: 'social' },
  { id: 't3-york-20', text: '[Subject] is typically a hardy little dog who stays active and playful for many years.' },
  { id: 't3-york-21', text: '[Name] often has a funny way of giving you a look when [Subject] wants more attention.' },
  { id: 't3-york-22', text: '[Subject] is often a gentle companion who enjoys soft brushing and affection.', tone: 'cuddly' },
  { id: 't3-york-23', text: '[Name] is usually an explorer at heart and may enjoy a safe yard to sniff around in.' },
  { id: 't3-york-24', text: '[Subject] is often a very loyal companion who stays close to [Possessive] people.', idea: 'bonding' },
  { id: 't3-york-25', text: '[Name] is a [Color] [Breed] who is often just as lovely in personality as [Subject] is in appearance.' },
];

/** Fallback Tier 3 when breed is unknown/other (neutral trait lines from Golden Doodles set, no breed-specific claims). */
const TIER3_FALLBACK: ContentLine[] = [
  { id: 't3-fb-01', text: '[Name] usually adapts well to different home routines and family lifestyles.' },
  { id: 't3-fb-02', text: '[Subject] tends to have a gentle way of playing with toys and people alike.' },
  { id: 't3-fb-03', text: 'This puppy is often very observant and may quickly learn the rhythm of your home.' },
  { id: 't3-fb-04', text: '[Name] often brings together a loving heart and a bright, curious mind.', idea: 'bonding' },
  { id: 't3-fb-05', text: '[Subject] is often motivated by snacks, which can make teaching manners a lot of fun.' },
  { id: 't3-fb-06', text: '[Name] usually enjoys games that keep [Possessive] mind busy and engaged.' },
  { id: 't3-fb-07', text: '[Subject] often has an active side that fits well with families who enjoy walks and outings.', tone: 'active' },
  { id: 't3-fb-08', text: '[Name] is often very tuned in to the people around [Object].' },
  { id: 't3-fb-09', text: '[Subject] typically has a sturdy frame that is made for both play and snuggles.', tone: 'cuddly' },
  { id: 't3-fb-10', text: '[Name] is often a great match for families looking for a lively and loving companion.' },
];

/** Map canonical breed (or "other") to Tier 3 content key. Poodle, Mini Poodle, Mini Doodle -> Poodle set. */
export const BREED_TO_TIER3_KEY: Record<string, string> = {
  'Golden Doodles': 'Golden Doodles',
  'Shih Tzu': 'Shih Tzu',
  'Labradoodles': 'Labradoodles',
  'Maltese': 'Maltese',
  'Poodle': 'Poodle',
  'Mini Poodle': 'Poodle',
  'Mini Doodle': 'Poodle',
  'Chihuahua': 'Chihuahua',
  'Yorkies': 'Yorkies',
};

export const TIER3_BY_BREED: Tier3Content = {
  'Golden Doodles': TIER3_GOLDEN_DOODLES,
  'Shih Tzu': TIER3_SHIH_TZU,
  'Labradoodles': TIER3_LABRADOODLES,
  'Maltese': TIER3_MALTESE,
  'Poodle': TIER3_POODLE,
  'Chihuahua': TIER3_CHIHUAHUA,
  'Yorkies': TIER3_YORKIES,
  fallback: TIER3_FALLBACK,
};

/** Tier 4: Unique behavioral quirks (30 variations) */
export const TIER4_QUIRKS: Tier4Content = [
  { id: 't4-01', text: 'You will love how [Name] rests [Possessive] head right on your knee when [Subject] wants a little love.', tone: 'cuddly' },
  { id: 't4-02', text: '[Subject] often lets out a long and content sigh right before falling into a puppy nap.' },
  { id: 't4-03', text: '[Name] loves carrying [Possessive] favorite soft toy around the house like a special prize.', tone: 'playful' },
  { id: 't4-04', text: 'One charming quirk is how [Subject] dramatically tilts [Possessive] head when you talk directly to [Object].' },
  { id: 't4-05', text: '[Name] often does a big stretch and a little yawn whenever [Subject] first wakes up.' },
  { id: 't4-06', text: 'You will notice that [Possessive] tail starts thumping on the floor the moment you make eye contact.' },
  { id: 't4-07', text: '[Subject] often curls up into a tight little circle when resting in [Possessive] favorite spot.', tone: 'cuddly' },
  { id: 't4-08', text: 'It is common for [Name] to gently nudge your hand with [Possessive] nose when [Subject] wants pets.' },
  { id: 't4-09', text: '[Subject] usually finds a sunny patch of floor and loves sleeping right in the warm light.' },
  { id: 't4-10', text: 'You will often see [Name] twitching [Possessive] paws and letting out tiny dream barks while napping.' },
  { id: 't4-11', text: '[Subject] has an endearing way of sitting very still and watching you go about your day.' },
  { id: 't4-12', text: 'Whenever you come home, [Name] often greets you by picking up the nearest toy to show it off.', tone: 'playful' },
  { id: 't4-13', text: '[Subject] loves to burrow under a soft blanket until only [Possessive] little nose is sticking out.', tone: 'cuddly' },
  { id: 't4-14', text: 'You will frequently find [Name] resting [Possessive] chin flat on [Possessive] front paws while relaxing.' },
  { id: 't4-15', text: '[Subject] has a sweet habit of leaning [Possessive] whole body against your legs as a sign of affection.', idea: 'affection' },
  { id: 't4-16', text: '[Name] has a funny habit of army-crawling across the carpet when [Subject] feels extra playful.', tone: 'playful' },
  { id: 't4-17', text: 'One adorable trait is how [Subject] waits by the door and dances with [Possessive] front paws when you arrive.' },
  { id: 't4-18', text: '[Name] often sleeps on [Possessive] back with all four paws in the air, looking completely relaxed.' },
  { id: 't4-19', text: '[Subject] sometimes grooms [Possessive] toys by licking them as if they were little friends.' },
  { id: 't4-20', text: '[Name] is very observant and often tilts [Possessive] head at every new sound in the kitchen.' },
  { id: 't4-21', text: '[Subject] has a habit of talking back with soft little whimpers when [Subject] gets excited.' },
  { id: 't4-22', text: 'You might catch [Name] trying to hide a favorite treat under the edge of [Possessive] bed for later.' },
  { id: 't4-23', text: '[Subject] often loves sitting right on your feet, making sure you do not go far without [Object].', idea: 'bonding' },
  { id: 't4-24', text: 'One sweet quirk is how [Name] tries to share a favorite toy by dropping it right on your foot.', tone: 'playful' },
  { id: 't4-25', text: '[Subject] sometimes does a happy spin in a tight circle before settling down for a meal.' },
  { id: 't4-26', text: '[Name] has a funny way of sneezing when [Subject] is excited and ready to play.' },
  { id: 't4-27', text: 'You will love how [Subject] carefully inspects every new grocery bag that comes into the house.' },
  { id: 't4-28', text: '[Name] often rests [Possessive] chin on your arm while you are sitting down or using your phone.', tone: 'cuddly' },
  { id: 't4-29', text: '[Subject] sometimes tries to help make the bed by diving under the sheets.' },
  { id: 't4-30', text: 'One endearing trait is how [Name] waits for you to wake up by sitting patiently nearby.', idea: 'bonding' },
];

/** Tier 5: Closings & family placement (30 variations) */
export const TIER5_CLOSINGS: Tier5Content = [
  { id: 't5-01', text: '[Name] will likely make a wonderful addition to a loving household.' },
  { id: 't5-02', text: 'If you are seeking a loyal companion to complete your family, [Name] is ready to meet you.' },
  { id: 't5-03', text: 'Ready to settle into a loving environment, [Subject] could be a great match for many kinds of homes.' },
  { id: 't5-04', text: 'With an adaptable nature, [Name] will likely settle in well with time, routine, and affection.' },
  { id: 't5-05', text: 'Do not miss the chance to welcome this incredible [Breed] into your home and start a new adventure together.' },
  { id: 't5-06', text: '[Name] is already showing so much promise and could become the heart of [Possessive] new home.' },
  { id: 't5-07', text: 'This sweet [Color] pup is happy, well cared for, and ready to meet [Possessive] forever family.' },
  { id: 't5-08', text: '[Subject] is a truly special puppy who deserves a home filled with just as much love as [Subject] gives.' },
  { id: 't5-09', text: '[Name] is up to date on [Possessive] care and waiting for the right family to come along.' },
  { id: 't5-10', text: 'Whether your home is big or small, [Name] is ready to become part of your daily life.' },
  { id: 't5-11', text: '[Subject] brings together sweetness and smarts and is ready to be someone\'s new best friend.' },
  { id: 't5-12', text: '[Name] has been raised with a lot of love, and it shows in [Possessive] sweet temperament.' },
  { id: 't5-13', text: 'If you want a dog that is affectionate, bright, and fun to be around, [Name] may be the one for you.' },
  { id: 't5-14', text: 'This [Color] [Breed] will likely bring a lot of joy, laughter, and companionship into the right home.' },
  { id: 't5-15', text: '[Name] is looking for a family that will cherish [Object] and include [Object] in everyday life.' },
  { id: 't5-16', text: '[Subject] is social, loving, and ready to begin life with a family of [Possessive] own.', idea: 'social' },
  { id: 't5-17', text: '[Name] is a gentle soul who would love a home filled with kindness, patience, and affection.' },
  { id: 't5-18', text: 'Your search for a wonderful [Breed] may end here with [Name].' },
  { id: 't5-19', text: '[Subject] is ready to fill your home with wagging tails and puppy love.' },
  { id: 't5-20', text: 'Come meet [Name] and see for yourself why this [Age]-old pup is so special.' },
  { id: 't5-21', text: '[Name] is a bundle of joy who is ready to turn a house into a home.' },
  { id: 't5-22', text: 'This [Color] [Breed] is a playful and loving companion who is ready for the right family.' },
  { id: 't5-23', text: '[Subject] is a smart and eager pup who will likely be noticed wherever [Subject] goes.' },
  { id: 't5-24', text: '[Name] has the kind of temperament that can be appreciated by both first-time and experienced dog owners.' },
  { id: 't5-25', text: 'We are excited to see [Name] find the loving family [Subject] deserves.' },
  { id: 't5-26', text: '[Subject] is a loyal companion who will want to be by your side through everyday life.' },
  { id: 't5-27', text: '[Name] is a one-of-a-kind puppy who is ready to be loved and adored.' },
  { id: 't5-28', text: 'With [Name] in your life, each day may feel a little brighter and a lot more fun.' },
  { id: 't5-29', text: '[Subject] is a vibrant [Breed] who is ready to grow up alongside a caring family.' },
  { id: 't5-30', text: '[Name] is ready to begin [Possessive] happily ever after with the right home.' },
];
